- hosts: dev
  remote_user: ec2-user
  become: yes
  tasks:
  
    - name: install pip
      yum:
        name: python-pip
        state: present

    - name: install docker
      yum:
        name: docker
        state: present

    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes   

    - name: install docker py
      pip:
        name: docker.py

    - name: container
      docker_container:
        name: tomcattest
        image: "ajayganesh/myweb:0.0.2"
        state: started
        ports:
          -"8080:9090"
