- hosts: dev
  remote_user: ec2-user
  become: yes
  tasks:

    - name: install docker
      yum:
        name: docker
        state: present

    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes   

    - name: install docker py
      pip:
        name: docker.py
        service: present

    - name: container
      docker_container:
        name: tomcattest
        image: "ajayganesh/myweb:0.0.2"
        state: started
        ports:
          -"80:9090"

